import { gsap } from 'gsap';
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import { useLayoutEffect, useRef } from "react";
// import Button from '@mui/material/Button';
import { BsArrowRight } from "react-icons/bs";
import MyButton from '../components/MyButton';
import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const comp = useRef(); // create a ref for the root level element (for scoping)
  const circle = useRef();
  gsap.registerPlugin(ScrollTrigger);

  useLayoutEffect(()=>{
    const parallax = document.getElementById('parallax')!
    const cloud1 = document.getElementById('cloud1')!
    const cloud2 = document.getElementById('cloud2')!
    const cloud3 = document.getElementById('cloud3')!
    const plane = document.getElementById('plane')!
    const main = document.getElementById('main')!
    const boxes = gsap.utils.toArray<HTMLElement>('.box')!
    console.log(boxes)
    window.addEventListener("scroll", function () {
      let offset = window.pageYOffset;
      // parallax.style.backgroundPositionY = offset * 0.7 + "px";
        main.style.backgroundPositionY = offset * 0.1 + "px";
        console.log(offset)
        cloud2.style.top = offset * -.1 +'px'
        cloud1.style.top = offset * -0.2 +'px'
        cloud3.style.top = offset * -0.3 +'px'
      // plane.style.left = offset * 5.5 +'px'
      // plane.style.left = offset * 2 + 'px'
      // DIV 1 background will move slower than other elements on scroll.
    });
    var textheight = document.getElementById("bigtextcn")!.offsetHeight * -0.08;
        console.log(textheight)
      const ctx = gsap.context((self) => {
        const parallax = document.getElementById('parallax');
        let plane = document.querySelector("#plane");
        
        gsap.to("#parallax",{scrollTrigger:{
          trigger: "#parallax",
          pin: true,
          pinSpacing: false,
          start: "top top",
          end: "bottom top",
          scrub: 1
        }});  
        gsap.to("#plane",{
          y: -380,
          x: 1000,
          rotation: 0.01,
          duration: 3000,
          // ease: "power1.out",
          scrollTrigger: {
              trigger: "body",
              start: "top top",
              end: "+=500",
              scrub: 1,
              // onEnter: function() { gsap.to("#plane", { scaleX: 1, rotation: 0 }) },
              // onLeave: function() { gsap.to("#plane", { scaleX: 1, rotation: 0 }) },
          }
        });   
        gsap.to("#text1",{
          y: -textheight,
          x: 0,
          // ease: "power1.out",
          scrollTrigger: {
              trigger: "body",
              start: "top top",
              end: "+=500",
              scrub: 1,
              // onEnter: function() { gsap.to("#plane", { scaleX: 1, rotation: 0 }) },
              // onLeave: function() { gsap.to("#plane", { scaleX: 1, rotation: 0 }) },
          }
        });   
        gsap.to("#text2",{
          y: textheight,
          x: 0,
          // color: '#EE6C4D',
          color: '#FF9FA8',
          ease: "power1.out",
          scrollTrigger: {
              trigger: "body",
              start: "top top",
              end: "+=500",
              scrub: 1,
              onEnter: function() { gsap.to("#plane", { scaleX: 1, rotation: 0 }) },
              onLeave: function() { gsap.to("#plane", { scaleX: 1, rotation: 0 }) },
          }
        });   
       
        // boxes.forEach((box, i) => {
        //   // const anim = gsap.fromTo(box, {autoAlpha: 0, y: 50}, {duration: 1, autoAlpha: 1, y: 0});
        //   gsap.to(box!,{
        //   scrollTrigger: {
        //     trigger: box,
        //     // animation: anim,
        //     toggleActions: 'play none none none',
        //     once: true,
        //   }})
        // });
        gsap.utils.toArray<HTMLElement>('.box').forEach(box => {
          gsap.fromTo(box, {
              autoAlpha: 0, 
              y: 50
            }, {
            scrollTrigger: {
              trigger: box,
              once: true
            },
            duration: 1, 
            autoAlpha: 1, 
            y: 0
          });
        });
        gsap.utils.toArray<HTMLElement>('.box2').forEach(box => {
          gsap.fromTo(box, {
              autoAlpha: 0, 
              y: 50,
            }, {
            scrollTrigger: {
              trigger: box,
              once: true,
            },
            duration: 1, 
            autoAlpha: 1, 
            y: 0,
          });
        });

      })
      return () => ctx.revert(); // cleanup
  }, [])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* CLASSES FOR OVAL THING: h-[1000rem]  */}
      <section id='parallax' className={`z-1 h-[100vh] fixed top-0 xl:h-[100vh] bg-100vh w-full bg-[#1fa0e0] bg-center `}>
       <Image id="parallaximg" src='/cloudedsky1.webp' width={100} height={100} alt="plane image" className='absolute top-0 left-0 z-10 w-[100vw] h-[140vh] object-cover' unoptimized></Image>

        <div id="bigtextcn" className='text-[#133C54] w-full text-center absolute top-[50vh] left-[50vw] translate-y-[-50%] translate-x-[-50%] z-20 text-[10rem] max-md:text-[7.4rem]'>
          <h1 id="text1" className='box2 parallaxTitle'>WELCOME TO</h1>
          <h1 id="text2" className='box2 parallaxTitle'>D.AVIATION</h1>
        </div>
        <Image id="plane" src='/plane-assets/daviation-plane-xl.webp'
        width={100} height={100} alt="plane image" className='absolute  top-[50vh] left-[50vw] translate-y-[-50%] translate-x-[-50%] z-20 w-full h-auto max-w-[70rem]' blurDataURL="URL"
        placeholder="blur" unoptimized priority></Image>
        
      </section>


      <main id='main' className={`
      relative
       h-full pt-20 bg-white`}
      >
        <div className='w-[130vw] z-10  opacity-100 brightness-200	 gray-scale-[50%] absolute -top-[8rem] min-[1500px]:-top-[10rem] min-[1300px]:-top-[20rem] xsm:-top-[14rem]'>
          <Image id="cloud1" className="w-full 
          xl:w-[70%] xl:mt-[5rem]
          -right-[80%] z-10 -left-20 absolute -top-40" src='/Cloud1.webp' width={100} height={100} alt="cloudimage1"></Image>
          <Image id="cloud2" className="w-full xl:w-[70%] xl:mt-20 -left-[10%] z-10  absolute top-0 min-[1400px]:-top-20" src='/Clouds2.webp' width={100} height={100} alt="cloudimage1"></Image>
          <Image id="cloud3" className="w-full xl:w-[40%] xl:left-[60%] lg:mt-[10rem] -left-[30%] z-10 absolute -top-40 " src='/Clouds3.webp' width={100} height={100} alt="cloudimage1"></Image>
        </div>
        
        <section id='section1' className='z-20 max-w-[1700px] grid grid-cols-1 md:grid-cols-4 text-center md:text-start relative h-fit pt-[10rem] w-[80vw] justify-between gap-12 m-auto max-md:flex-col items-center'>
          <div className='firstdiv flex md:col-span-2 order-last md:order-first gap-4 flex-col align-start '>
            <div className="box flex flex-col gap-2 mb-4">
              <h3 className='ml-1 box'>ABOUT US</h3>
              <h1 className="text-[3rem] box leading-[3.2rem]  text-[#133C54] font-bold">Educating students on <span className='text-[#FFA0A9] text-[3rem] font-bold'>aviation</span></h1>
            </div>
            <p className='box text-[1.1rem] font-normal	'>We are a student led aviation/drone team providing on-hands learning opportunities for students. You'll get to learn all aspects of drone building, from start to finish. These include: 3d modeling in CAD, programming for drone automation, and fabrication.  Everyone is welcome!</p>
            <div className='box w-fit max-md:m-auto'>
            <MyButton text={"Join Now!"}></MyButton>
            </div>
          </div>
          <div className="seconddiv md:col-span-2 max-md:justify-self-center max-md:max-w-[28rem] md:max-xl:min-w-[40rem] xl:justify-self-end min-[1800px]:justify-self-center rounded-md box">
            <img className='z-20 rounded-md' src="/daviation-image-blob.webp" alt="about us image" />
          </div>
        </section>


        <section className='z-20 max-w-[1700px] py-[6rem] grid grid-cols-1 md:grid-cols-4 text-center md:text-start relative h-fit w-[80vw] justify-between gap-4 m-auto max-md:flex-col items-center '>
          <div className="md:col-span-3 col-span-4 rounded-md ">
            <img className='box z-20 rounded-md' src="/drone-img.webp" alt="about us image" />
          </div>
          <div className='flex col-span-4 md:col-span-1 gap-4 flex-col md:ditems-start items-center'>
            <div className="box flex flex-col gap-2">
              <h1 className="text-[3rem] leading-[3.2rem]  text-[#133C54] font-bold">Our Drone</h1>
            </div>
            <div className='w-fit box see-more hover:brightness-120 cursor-pointer gap-2 whitespace-nowrap flex text-[#5089A8] items-center max-sm:m-auto'>
              See more photos
              <BsArrowRight className='stroke-1 BsArrowRight'></BsArrowRight>
            </div>
          </div>
        </section>
        {/* <section className='relative grid grid-cols-1 sm:grid-cols-5 py-[10rem] w-full max-w-[80vw] justify-between gap-12 m-auto max-md:flex-col items-start'>
          <div className='flex col-span-2 gap-2 flex-col align-start '>
            <h1 className="text-[2rem] font-medium">Photos!</h1>
            <p>Check out some awesome photos of the program.</p>
            <Button type="primary"  className='bg-primary mt-5' color="primary" variant="contained">View Gallery</Button>
          </div>
          <div className="grid col-span-3 grid-cols-1 sm:grid-cols-2 gap-4 rounded-md">
            <div className="relative rounded-md">
              <img src="https://coresites-cdn-adm.imgix.net/mpora_new/wp-content/uploads/2021/03/how-to-build-your-own-fpv-drone-jt.jpg?fit=crop" alt="Image 1" className="w-full h-full object-cover" />
            </div>
            <div className="relative rounded-md">
              <img src="https://s4.reutersmedia.net/resources/r/?m=02&d=20170321&t=2&i=1177436023&w=&fh=545&fw=810&ll=&pl=&sq=&r=2017-03-21T174509Z_25997_MRPRC13F2549640_RTRMADP_0_USA-DRONE-HUNTER" alt="Image 2" className="w-full h-full object-cover" />
            </div>
            <div className="relative rounded-md">
              <img src="https://www.cpomagazine.com/wp-content/uploads/2018/04/eye-in-the-sky-drone-surveillance-and-privacy_1500.jpg" alt="Image 3" class="w-full h-full object-cover" />
            </div>
            <div className="relative rounded-md">
              <img src="https://diginomica.com/sites/default/files/images/2020-09/drone-2816244_1280_0.jpg" alt="Image 4" className="w-full h-full object-cover" />
            </div>
          </div>
        </section> */}


        <footer className="bg-[#303356] text-gray-300">
          <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
            <div className="md:flex md:items-center md:justify-between">
              <div className="flex justify-center md:order-2">
                <a href="#" className="text-gray-400 hover:text-gray-500 ml-6">
                  <span className="sr-only">Facebook</span>
                  <svg className="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                    <path
                      d="M20 3h-3.82c-.78 0-1.47.47-1.77 1.16l-1.57 3.89-.43 1.06h-6.01l-.43-1.06-1.57-3.89A1.99 1.99 0 0 0 4.82 3H1a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h3.82c.78 0 1.47-.47 1.77-1.16l1.57-3.89.43-1.06h6.01l.43 1.06 1.57 3.89c.3.69.99 1.16 1.77 1.16H20a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1z" />
                  </svg>
                </a>
                <a href="#" className="text-gray-400 hover:text-gray-500 ml-6">
                  <span className="sr-only">Twitter</span>
                  <svg className="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                    <path
                      d="M23.998 4.569a9.29 9.29 0 0 1-2.675.73A4.65 4.65 0 0 0 23.304 3.1a9.232 9.232 0 0 1-2.944 1.128A4.612 4.612 0 0 0 15.912 0c-2.536 0-4.594 2.058-4.594 4.593 0 .36.04.712.112 1.05A13.112 13.112 0 0 1 1.568 1.268a4.55 4.55 0 0 0-.633 2.312c0 1.594.81 2.996 2.04 3.82a4.617 4.617 0 0 1-2.09-.577v.056c0 2.223 1.582 4.072 3.683 4.498a4.704 4.704 0 0 1-1.23.164c-.298 0-.586-.027-.875-.083a4.627 4.627 0 0 0 4.312 3.206 9.33 9.33 0 0 1"
                    />
                  </svg>
                </a>
                <a href="#" className="text-gray-400 hover:text-gray-500 ml-6">
                  <span className="sr-only">GitHub</span>
                  <svg className="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                    <path fill-rule="evenodd"
                      d="M12 0C5.373 0 0 5.373 0 12c0 5.305 3.438 9.8 8.207 11.387.6.111.793-.26.793-.576 0-.284-.011-1.04-.015-2.042-3.338.724-4.042-1.609-4.042-1.609-.545-1.384-1.333-1.753-1.333-1.753-1.089-.744.084-.729.084-.729 1.205.084 1.838 1.236
                      1.838 1.236 1.07 1.844 2.809 1.309 3.495.999.108-.776.419-1.309.762-1.607-2.665-.304-5.466-1.307-5.466-5.816 0-1.284.459-2.335 1.236-3.164-.124-.303-.536-1.504.117-3.132 0 0 1.002-.319 3.276 1.212.95-.265 1.968-.397 2.982-.402 1.014.005 2.032.137
                      2.982.402 2.273-1.531 3.276-1.212 3.276-1.212.653 1.628.242 2.829.118 3.132.776.829 1.235 1.879 1.235 3.164 0 4.518-2.804 5.51-5.479 5.807.429.36.813 1.089.813 2.195 0 1.586-.015 2.862-.015 3.248 0 .319.192.694.798.576C20.567 21.795 24 17.31
                      24 12c0-6.627-5.373-12-12-12z"
                      clip-rule="evenodd" />
                  </svg>
                </a>
              </div>
              <div className="mt-8 md:mt-0 md:order-1">
                <p className="text-center text-base">&copy; 2023 D.Aviation Corporation. All rights reserved.</p>
              </div>
            </div>
            </div>
          </footer>







        {/* <BackgroundImg></BackgroundImg> */}
          {/* <img className={styles.backgroundImg} src={"https://upload.wikimedia.org/wikipedia/commons/d/d9/Plane_Flying_Past_Mount_Kinabalu.jpg"}  /> */}
      </main>
      
    </>
  )
}
